---
- name: Instalación y despliegue de contenedor Apache en nodos EC2
  hosts: all
  become: true

  tasks:
    - name: Instalar dependencias para Docker
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Agregar clave GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Agregar repositorio de Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Instalar Docker Engine
      apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Verificar estado de instalación de Docker
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Mostrar versión de Docker
      debug:
        msg: "Docker instalado: {{ docker_version.stdout }}"

    - name: Iniciar servicio Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Descargar imagen httpd (Apache)
      docker_image:
        name: httpd
        source: pull

    - name: Verificar imagen descargada
      command: docker images httpd
      register: httpd_image
      changed_when: false

    - name: Mostrar estado de imagen httpd
      debug:
        msg: "Imagen httpd descargada: {{ httpd_image.stdout_lines }}"

    - name: Lanzar contenedor Apache
      docker_container:
        name: apache_web
        image: httpd
        state: started
        ports:
          - "80:80"
